"""add user_id to existing tables

Revision ID: d17e4cb59ebd
Revises: 1204d671f551
Create Date: 2026-08-13 12:56:49.101905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17e4cb59ebd'
down_revision: Union[str, Sequence[str], None] = '1204d671f551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_foreign_key(None, 'goals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('review_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'review_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('review_schedules', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_review_schedules_user_id'), 'review_schedules', ['user_id'], unique=False)
    op.create_foreign_key(None, 'review_schedules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('study_sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'study_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('subjects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('subjects_name_key'), 'subjects', type_='unique')
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    op.create_unique_constraint('uq_subjects_user_id_name', 'subjects', ['user_id', 'name'])
    op.create_foreign_key(None, 'subjects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('topics', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_topics_user_id'), 'topics', ['user_id'], unique=False)
    op.create_foreign_key(None, 'topics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_index(op.f('ix_topics_user_id'), table_name='topics')
    op.drop_column('topics', 'user_id')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint('uq_subjects_user_id_name', 'subjects', type_='unique')
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.create_unique_constraint(op.f('subjects_name_key'), 'subjects', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('subjects', 'user_id')
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_column('study_sessions', 'user_id')
    op.drop_constraint(None, 'review_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_review_schedules_user_id'), table_name='review_schedules')
    op.drop_column('review_schedules', 'user_id')
    op.drop_constraint(None, 'review_logs', type_='foreignkey')
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_column('review_logs', 'user_id')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_column('goals', 'user_id')
    # ### end Alembic commands ###
